aws:
  region: 'eu-west-1'
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/022612279290/migration-records'
  credentials:
    accessKeyId: 'AKIAIO7DX4WKCFXZ2AQA'
    secretKey: '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'
  client:
    max-connections: 512

script:
  thread-pool-size: 512
  wait-for-tasks-to-complete-on-shutdown: true
  await-termination-seconds: 3600